yarnPath: ".yarn/releases/yarn-berry.cjs"
npmRegistryServer: "https://registry.npm.taobao.org"

# 如果工程跑不起来可以先尝试增加下面的配置：

# 默认 pnp 可更换为原来的方式：node-modules
nodeLinker: "node-modules"

# pnpMode默认为"strict"，这种情况下所有用到的依赖都必须显式地声明在package.json中，
# 也就是说如果你的模块声明了webpack作为依赖，webpack中声明了acorn作为依赖，
# 在"strict"模式下你的模块不能直接引入acron，否则会报错。
# 而"loose"模式下是允许的，但却不是推荐用法。
pnpMode: "loose"
